name: Build Tauri para Windows

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Instalar dependências Node
      run: npm install
      working-directory: ./frontend

    - name: Build do Tauri
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: ./src-tauri
        frontendDist: ../frontend/dist

    - name: Salvar Instalador
      uses: actions/upload-artifact@v4
      with:
       name: meu-instalador-windows
       path: src-tauri/target/release/bundle/nsis/*.exe
